# Generated by Django 3.1.3 on 2020-11-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffhsleads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='message_telefon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
