# Generated by Django 3.1.3 on 2020-11-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffhsleads', '0002_auto_20201117_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='message_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sender',
            name='message_vorname',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
